=== bittools/skyhub-magento2/etc/skyhub.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="skyhub" type="skyhubConfig" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="skyhubConfig">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="catalog" type="catalogParameters" />
        </xs:sequence>
    </xs:complexType>
    <!-- CATALOG -->
    <xs:complexType name="catalogParameters">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="product" type="productConfig" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="productConfig">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="attributes" type="productAttributes"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="productAttributes">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="attribute" type="attributeData"/>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="blacklist" type="blacklistedAttributes" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="blacklistedAttributes">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="attribute" type="blacklistedAttributeConfig" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="blacklistedAttributeConfig">
        <xs:attribute name="code" type="xs:string" use="required"/>
    </xs:complexType>
    <!-- ATTRIBUTES LIST -->
    <xs:complexType name="attributesList">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="attribute" type="attributeData" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="attributeData">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="label" type="xs:string" nillable="false"/>
            <xs:element minOccurs="0" maxOccurs="1" name="description"/>
            <xs:element minOccurs="0" maxOccurs="1" name="validation" nillable="false"/>
            <xs:element minOccurs="0" maxOccurs="1" name="attribute_install_config" type="attributeInstallConfig" />
        </xs:sequence>
        <xs:attribute name="code" type="xs:string" use="required"/>
        <xs:attribute name="type" type="attributeTypes" />
        <xs:attribute name="input" type="inputTypes" />
        <xs:attribute name="cast_type" type="castTypes" default="string" />
        <xs:attribute name="required" type="xs:boolean" default="false" />
        <xs:attribute name="enabled" type="xs:boolean" default="false" />
        <xs:attribute name="editable" type="xs:boolean" default="true" />
    </xs:complexType>
    <xs:complexType name="attributeInstallConfig">
        <xs:sequence>
            <xs:element name="attribute_code" type="xs:string"/>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="backend_model"/>
            <xs:element name="type"/>
            <xs:element name="input" type="inputTypes"/>
            <xs:element name="source_model"/>
            <xs:element name="required" type="xs:boolean"/>
            <xs:element name="source" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <!-- REUSABLE SIMPLE TYPES -->
    <xs:simpleType name="castTypes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="float"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="attributeTypes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="varchar"/>
            <xs:enumeration value="decimal"/>
            <xs:enumeration value="int"/>
            <xs:enumeration value="datetime"/>
            <xs:enumeration value="static"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="inputTypes">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="select"/>
            <xs:enumeration value="multiselect"/>
            <xs:enumeration value="checkbox"/>
            <xs:enumeration value="radio"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== bittools/skyhub-magento2/etc/skyhub.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:BitTools_SkyHub:etc/skyhub.xsd">
    <skyhub>
        <catalog>
            <product>
                <attributes>
                    <attribute code="sku" enabled="true" required="true" editable="true">
                        <label>Product Sku</label>
                        <description>The product's main SKU (Stock Keeping Unit).</description>
                        <validation/>
                        <attribute_install_config>
                            <attribute_code>sku</attribute_code>
                            <label>SKU</label>
                            <backend_model>catalog/product_attribute_backend_sku</backend_model>
                            <type>static</type>
                            <input>text</input>
                            <source_model/>
                            <required>true</required>
                        </attribute_install_config>
                    </attribute>
                    <attribute code="name" enabled="true" required="true" editable="true">
                        <label>Product Name</label>
                        <description>The product's name.</description>
                        <validation/>
                        <attribute_install_config>
                            <attribute_code>name</attribute_code>
                            <label>Product Name</label>
                            <backend_model/>
                            <type>varchar</type>
                            <input>text</input>
                            <source_model/>
                            <required>true</required>
                        </attribute_install_config>
                    </attribute>
                    <attribute code="description" enabled="true" required="true" editable="true">
                        <label>Product Description</label>
                        <description>The product's description.</description>
                        <validation/>
                        <attribute_install_config>
                            <attribute_code>description</attribute_code>
                            <label>Product Description</label>
                            <backend_model/>
                            <type>varchar</type>
                            <input>text</input>
                            <source_model/>
                            <required>true</required>
                        </attribute_install_config>
                    </attribute>
                    <attribute code="status" enabled="true" cast_type="boolean" required="true" editable="true">
                        <label>Product Status</label>
                        <description>The product status that identifies if the product is enabled or disabled.</description>
                        <attribute_install_config>
                            <attribute_code>status</attribute_code>
                            <label>Product Status</label>
                            <backend_model/>
                            <type>int</type>
                            <input>select</input>
                            <source_model/>
                            <required>true</required>
                        </attribute_install_config>
                    </attribute>
                    <!--
                    <attribute code="qty" cast_type="float" type="varchar" input="text" enabled="false" required="false" editable="false">
                        <label>Product Stock Quantity</label>
                        <description>The products stock quantity available in store.</description>
                    </attribute>
                    -->
                    <attribute code="price" enabled="true" cast_type="float" required="true" editable="true">
                        <label>Product Price</label>
                        <description>The product's current price.</description>
                        <validation/>
                        <attribute_install_config>
                            <attribute_code>price</attribute_code>
                            <label>Product Price</label>
                            <backend_model/>
                            <type>decimal</type>
                            <input>text</input>
                            <source_model/>
                            <required>true</required>
                        </attribute_install_config>
                    </attribute>
                    <attribute code="promotional_price" enabled="true" required="true" cast_type="float" editable="true">
                        <label>Product Promotional Price</label>
                        <description>The product's current promotional price.</description>
                        <validation/>
                        <attribute_install_config>
                            <attribute_code>special_price</attribute_code>
                            <label>Product's promotional price.</label>
                            <backend_model/>
                            <type>decimal</type>
                            <input>text</input>
                            <source_model/>
                            <required>false</required>
                        </attribute_install_config>
                    </attribute>
                    <attribute code="cost" enabled="true" cast_type="float" required="true" editable="true">
                        <label>Product Cost</label>
                        <description>The product's cost.</description>
                        <validation/>
                        <attribute_install_config>
                            <attribute_code>cost</attribute_code>
                            <label>Product Cost</label>
                            <backend_model/>
                            <type>decimal</type>
                            <input>text</input>
                            <source_model/>
                            <required>false</required>
                        </attribute_install_config>
                    </attribute>
                    <attribute code="weight" enabled="true" cast_type="float" required="true" editable="true">
                        <label>Product Weight</label>
                        <description>The product's weight (in kilograms always).</description>
                        <validation/>
                        <attribute_install_config>
                            <attribute_code>weight</attribute_code>
                            <label>Product Weight</label>
                            <backend_model/>
                            <type>decimal</type>
                            <input>text</input>
                            <source_model/>
                            <required>true</required>
                        </attribute_install_config>
                    </attribute>
                    <attribute code="height" enabled="true" cast_type="float" required="true" editable="true">
                        <label>Product Height</label>
                        <description>The product's height (in centimeters always).</description>
                        <validation/>
                        <attribute_install_config>
                            <attribute_code>height</attribute_code>
                            <label>Product Height</label>
                            <backend_model/>
                            <type>decimal</type>
                            <input>text</input>
                            <source_model/>
                            <required>true</required>
                        </attribute_install_config>
                    </attribute>
                    <attribute code="width" enabled="true" cast_type="float" required="true" editable="true">
                        <label>Product Width</label>
                        <description>The product's width (in centimeters always).</description>
                        <validation/>
                        <attribute_install_config>
                            <attribute_code>width</attribute_code>
                            <label>Product Width</label>
                            <backend_model/>
                            <type>decimal</type>
                            <input>text</input>
                            <source_model/>
                            <required>true</required>
                        </attribute_install_config>
                    </attribute>
                    <attribute code="length" enabled="true" cast_type="float" required="true" editable="true">
                        <label>Product Length</label>
                        <description>The product's length (in centimeters always).</description>
                        <validation/>
                        <attribute_install_config>
                            <attribute_code>length</attribute_code>
                            <label>Product Length</label>
                            <backend_model/>
                            <type>decimal</type>
                            <input>text</input>
                            <source_model/>
                            <required>true</required>
                        </attribute_install_config>
                    </attribute>
                    <attribute code="brand" enabled="true" required="true" editable="true">
                        <label>Product Brand</label>
                        <description>The product's brand.</description>
                        <validation/>
                        <attribute_install_config>
                            <attribute_code>brand</attribute_code>
                            <label>Product Brand</label>
                            <backend_model/>
                            <type>int</type>
                            <input>select</input>
                            <source_model/>
